/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */


export interface paths {
  "/health": {
    get: {
      responses: {
        /** @description OK */
        200: {
          content: never;
        };
      };
    };
  };
  "/v1/meta/providers": {
    get: {
      responses: {
        /** @description OK */
        200: {
          content: never;
        };
      };
    };
  };
  "/v1/airports/search": {
    get: {
      parameters: {
        query: {
          query: string;
        };
      };
      responses: {
        /** @description OK */
        200: {
          content: {
            "application/json": {
              success?: boolean;
              data?: components["schemas"]["Airport"][];
            };
          };
        };
      };
    };
  };
  "/v1/flights/search": {
    post: {
      requestBody: {
        content: {
          "application/json": components["schemas"]["FlightSearchRequest"];
        };
      };
      responses: {
        /** @description OK */
        200: {
          content: {
            "application/json": {
              success?: boolean;
              data?: components["schemas"]["FlightOffer"][];
            };
          };
        };
      };
    };
  };
  "/v1/bookings/create": {
    post: {
      requestBody: {
        content: {
          "application/json": components["schemas"]["BookingCreate"];
        };
      };
      responses: {
        /** @description OK */
        200: {
          content: never;
        };
      };
    };
  };
  "/v1/admin/cache/purge": {
    post: {
      parameters: {
        header: {
          "x-staff-key": string;
        };
      };
      requestBody?: {
        content: {
          "application/json": {
            key?: string;
          };
        };
      };
      responses: {
        /** @description OK */
        200: {
          content: never;
        };
      };
    };
  };
}

export type webhooks = Record<string, never>;

export interface components {
  schemas: {
    Airport: {
      iata?: string;
      name?: string;
      city?: string;
      country?: string;
    };
    FlightSearchRequest: {
      origin: string;
      destination: string;
      /** Format: date */
      departDate: string;
      /** Format: date */
      returnDate?: string;
      /** @enum {string} */
      cabin?: "economy" | "premium_economy" | "business" | "first";
      adults: number;
      children?: number;
      infants?: number;
    };
    FlightOffer: {
      id?: string;
      carrier?: string;
      segments?: {
          from?: string;
          to?: string;
          /** Format: date-time */
          departAt?: string;
          /** Format: date-time */
          arriveAt?: string;
          carrier?: string;
        }[];
      price?: {
        amount?: number;
        currency?: string;
      };
      refundable?: boolean;
      changeable?: boolean;
      baggage?: string;
      deepLink?: string;
    };
    BookingCreate: {
      offerId?: string;
      /** Format: email */
      contactEmail?: string;
    };
  };
  responses: never;
  parameters: never;
  requestBodies: never;
  headers: never;
  pathItems: never;
}

export type $defs = Record<string, never>;

export type external = Record<string, never>;

export type operations = Record<string, never>;
