name: Purge Cloudflare on Vercel Production

on:
  deployment_status:
  workflow_dispatch:
    inputs:
      purge_all:
        description: Purge entire zone (true/false)
        required: false
        type: boolean
        default: false
      hosts:
        description: Space-separated hostnames to purge
        required: false
        default: "app.timagreentours.com timagreentours.com"

jobs:
  purge:
    if: >
      ${{ github.event_name == 'deployment_status' &&
          github.event.deployment_status.state == 'success' &&
          (github.event.deployment.environment == 'Production' || github.event.deployment.environment == 'production') }}
    runs-on: ubuntu-latest
    environment:
      name: Production
    permissions:
      contents: read
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v5
        with:
          node-version: 20

      - name: Purge Cloudflare cache (hosts)
        env:
          CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN || secrets.TGT_4cfapiT || vars.CLOUDFLARE_API_TOKEN || vars.TGT_4cfapiT }}
          CLOUDFLARE_ZONE_ID: ${{ secrets.CLOUDFLARE_ZONE_ID || secrets.TGT_4cfziD || vars.CLOUDFLARE_ZONE_ID || vars.TGT_4cfziD }}
        run: |
          set -e
          node -v
          echo "Deployment ${GITHUB_SHA} for environment: ${{ github.event.deployment.environment }}"
          if [ -z "${CLOUDFLARE_API_TOKEN:-}" ]; then echo "[workflow] CLOUDFLARE_API_TOKEN missing"; exit 1; fi
          if [ -z "${CLOUDFLARE_ZONE_ID:-}" ]; then echo "[workflow] CLOUDFLARE_ZONE_ID missing"; exit 1; fi
          # Host-level purge only for app + apex
          node scripts/purge-cloudflare.mjs app.timagreentours.com timagreentours.com

  manual:
    if: ${{ github.event_name == 'workflow_dispatch' }}
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v5
        with:
          node-version: 20

      - name: Purge via inputs
        env:
          CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN || secrets.TGT_4cfapiT || vars.CLOUDFLARE_API_TOKEN || vars.TGT_4cfapiT }}
          CLOUDFLARE_ZONE_ID: ${{ secrets.CLOUDFLARE_ZONE_ID || secrets.TGT_4cfziD || vars.CLOUDFLARE_ZONE_ID || vars.TGT_4cfziD }}
        run: |
          HOSTS="${{ github.event.inputs.hosts }}"
          PURGE_ALL="${{ github.event.inputs.purge_all }}"
          echo "Hosts: $HOSTS | Purge all: $PURGE_ALL"
          if [ "$PURGE_ALL" = "true" ]; then
            CF_PURGE_ALL=1 node scripts/purge-cloudflare.mjs
          else
            node scripts/purge-cloudflare.mjs $HOSTS
          fi
  workflow_run:
    workflows: ["CI"]
    types: [completed]

  purge_on_ci:
    if: >
      ${{ github.event_name == 'workflow_run' &&
          github.event.workflow_run.conclusion == 'success' &&
          github.event.workflow_run.head_branch == 'main' }}
    runs-on: ubuntu-latest
    environment:
      name: Production
    permissions:
      contents: read
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v5
        with:
          node-version: 20

      - name: Purge Cloudflare after CI success
        env:
          CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN || secrets.TGT_4cfapiT || vars.CLOUDFLARE_API_TOKEN || vars.TGT_4cfapiT }}
          CLOUDFLARE_ZONE_ID: ${{ secrets.CLOUDFLARE_ZONE_ID || secrets.TGT_4cfziD || vars.CLOUDFLARE_ZONE_ID || vars.TGT_4cfziD }}
        run: |
          set -e
          if [ -z "${CLOUDFLARE_API_TOKEN:-}" ]; then echo "[workflow] CLOUDFLARE_API_TOKEN missing"; exit 1; fi
          if [ -z "${CLOUDFLARE_ZONE_ID:-}" ]; then echo "[workflow] CLOUDFLARE_ZONE_ID missing"; exit 1; fi
          node scripts/purge-cloudflare.mjs app.timagreentours.com timagreentours.com
